---
title: "Publications"
date: 03/20/2024
output:
  prettydoc::html_pretty:
    highlight: github
    theme: cayman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Kassis, W.,  Aksoy, D., Favre, C., Gaugler, S., Grafinger, E., Artz, S., & Magnuson, D. (2024). On the complex relationship between resilience in adolescence despite parental physical abuse and hair cortisol levels: A fourth wave of resilience research. *Frontiers of Psychiatry--Adolescent and Young Adult Psychiatry,* 15: 13345844.  doi: 10.3389/fpsyt.2024.1345844   Available from: https://t.ly/15Xc9


Dobud, W., Harper, N., & Magnuson, D. (2024). Adolescent wilderness therapy: an exploration of how reasons for referral, client motivation for change, and clinical measures predict client outcomes. *Youth, 4*(1), 382-394. https://doi.org/10.3390/youth4010027

Benoit, C., Koenig, B., Mellor, A., Jansson, M., Magnuson, D. & Vetrone, L. (2024) Navigating Stigma in Romantic Relationships Where One or Both Partners Sell Sexual Services, *The Journal of Sex Research*, DOI: 10.1080/00224499.2024.2302974

Baldwin, C., & Magnuson, D. (2022). Program planner dignity and negotiation in collaborative projects. *Canadian Journal for the Study of Adult Education*, pp. 73-88. 

Jansson, M., Smith, M., Benoit, C., Magnuson, D., & Healey, P. (2022). Challenges and benefits of disclosure of sex work to intimate partners.  *Journal of Sex Research*. Available: https://www-tandfonline-com.ezproxy.library.uvic.ca/doi/full/10.1080/00224499.2022.2092587

Magnuson, D., Healey, P., Martinflatt, A., & McGrath, J. (2022). Measuring the qualities of a relationship. In J. Freeman, (Ed.), *Caring to Connect: Nurturing hopeful, healing relationships with young people.* The CYC-Net Press. 

Magnuson, D., Dobud, W., & Harper, N. (2022). Can involuntary youth transport into outdoor behavioural healthcare treatment programs (wilderness therapy) ever be ethical? *Child & Family Social Work.* https://doi-org.ezproxy.library.uvic.ca/10.1007/s10560-022-00864-2

Vetrone, L., Benoit, C., Magnuson, D. Jansson, S. M., Healey, P, & Smith, M. (2022). Education aspirations and barriers to achievement for street-involved youth in Victoria, Canada. *Social Inclusion, 10*(4). 

Tilstra, E., Magnuson, D., Harper, N. J., & Lepp, A. (2022). Gender and risk in outdoor adventure education. *Journal of Outdoor  and  Environmental Education.* https://doi.org/10.1007/s42322-022-00098-x

Magnuson, D. (2021) Doing ethics and the profession. In V. R. Mann-Feder (ed), *Doing Ethics in Child and Youth Care* (pp. 145-158). Canadian Scholars Press.

Harper, N. J., Magnuson, D., & Dobud, W. W. (2021). A closer look at involuntary treatment and the use of transport service in Outdoor Behavioral Healthcare. *Child & Youth Services.* Available online: https://www.tandfonline.com/doi/abs/10.1080/0145935X.2021.1938526?journalCode=wcys20

Magnuson, D., Jansson, M., & Benoit, C. (2021). The experience of emerging adulthood among street-involved youth. Oxford University Press. DOI: 10.1093/oso/9780190624934.003.0001

Modlin, H. & Magnuson, D. (2021). A constructive-developmental analysis of satisfaction, challenge, and coping in residential child care. *Child & Youth Services.* https://doi.org/10.1080/0145935X.2021.1903857

Baldwin, D., & Magnuson, D. (2020). Dignity affirmation and constraint in adult education program planners’ practice. Proceedings of the Adult Education in Global Times Conference/Actes de la Éducation des adults dans les temps globaux conférence (pp. 43-59). University of British Columbia, June. Available: https://edst-educ.sites.olt.ubc.ca/files/2020/06/aegt_proceedings_upload.pdf

Benoit, C., Jansson, M., Smith, M., Healey, P., & Magnuson, D. (2020). The relative quality of sex work. *Work, Employment, and Society.* https://doi.org/10.1177/0950017020936872

Benoit, C., Maurice, R., Abel, G., Smith, M., Jansson, M., Healey, P., & Magnuson, D. (2019). "I dodged the stigma bullet:" Canadian Sex Workers' situated response to occupational stigma. *Culture, Health, & Sexuality: An international journal for research, intervention, and care.* https://doi.org/10.1080/13691058.2019.1576226

Magnuson, D., Jansson, M., Benoit, C. (2019). Foster care as a support system for early leavers. In Varda Mann-Feder, (ed). *Leaving Care and the Transition to Adulthood: International Contributions to Theory, Research, and Practice.* Oxford University Press.

Snell, H. Stuart, C., & Magnuson, D. (2019). Post-secondary education as a crucible for learning practice. In K. Girabaghi & G. Charles (eds.), *Child & Youth Care Across Sectors vol 1.* Canadian Scholars Press. 

Carty, E., & Harper, N., & Magnuson, D. (2019). Outdoor adventure and CYC practice. In K. Girabaghi & G. Charles (eds.), *Child & Youth Care Across Sectors vol 1* Canadian Scholars Press. 

Benoit, C., Smith, M., Jansson, M., Healey, P., Magnuson, D. (2019). Effectiveness of anecdotes and logically false arguments to refute analysis based on systematically collected data. Archives of Sexual Behavior. 48:1903–1904. (article)

Benoit, C., Smith, M., Jansson, M., Healey, P., Magnuson, D. (2019). Unlinking prostitution and sex trafficking: Response to commentaries. Archives of Sexual Behavior. 48 (7), 1973–1980.

Benoit, C., Smith, M., Jansson, M., Healey, P., & Magnuson, D. (2018). The 'prostitution problem:' claims, evidence, and policy outcomes. *Archives of Sexual Behavior*: https://doi.org/10.1007/s10508-018-1276-6

Magnuson, D., Jansson, M., & Benoit, C. (2018). "I feel like I've really grown up: A brief report on street-involved youth. *Research to practice network, 2*(1). Available: https://fcssbc.ca/sf-docs/r2p/2018_magnuson.pdf
  
Kennedy, M.C., Jansson, M., Benoit, C., Magnuson, D., Scramstad, J., Halgrimsdottir, H. (2017). Social support among street-involved youth. *Journal of Youth Studies, 20*(10), pp. 1328-1345. http://dx.doi.org/10.1080/13676261.2017.1333582  

Magnuson, D., Jansson, M., Benoit, C., & Kennedy, M. C. (2015). Instability and caregiving in the lives of street-involved children from foster care. *Child and Family Social Work.*  http://doi.wiley.com/10.1111/cfs.12262

Magnuson, D. (2014). The productive use of conflict in child protection. *Social Sciences,* 672-686. https://www.mdpi.com/2076-0760/3/4/672/htm

Magnuson, D. (2014). Stop breaking people into bits: A plea for a peopled youthwork. In K. Gharabaghi, M. Krueger, & H. Skott-Myre (eds.), *With Children.* Wilfred Laurier Press.

Magnuson, D. & Baldin, C. (2014). A defence of professionalism: a response to Fusco and Baizerman. *Child & Youth Services, 35*(1). https://doi.org/10.1080/0145935X.2014.893741

Emerson, D., & Magnuson, D. (2013). Child protection intervention in domestic violence. An illustrative case narrative. *Child & Youth Services, 34*(3), 236-249. https://doi.org/10.1080/0145935X.2013.825546

Magnuson, D. (2011). Negotiation as a style in child protection work. *Child & Family Social Work.*  https://doi.org/10.1111/j.1365-2206.2011.00780.x

Magnuson, D. (2009). The need for the study of everyday life about youth work practice in divided societies. *Youth and Policy, 102*, 21-34.
	
Magnuson, D. (2009). The contribution of spirituality to “becoming a self” in child and youth services. In M. de Souza, L. Francis, J. O’Higgens-Norman, & D. Scott, (eds).  *International Handbook of Education for Spirituality, Care, and Well-being (pp. 433-452).* New York: Springer. https://link.springer.com/content/pdf/10.1007%2F978-1-4020-9018-9_24.pdf

Artz, S., Nicholson, D., & Magnuson, D. (2008). Examining sex differences in the use of direct and indirect aggression. *Gender Issues 25*(4), 267-288.
	
Magnuson, D. (2007). The perils, promise, and practice of youthwork in conflict societies. In D. Magnuson & M. Baizerman (Eds.), *Work with youth individed and contested societies.* Rotterdam: Sense Publishing. [edited volume also listed in books]
	
Magnuson, D. & Baizerman, M. (Eds.) (2007). *Work with youth in divided and contested societies.*  Rotterdam: Sense Publishing.
	
Romi, S., Magnuson, D., & Ferguson, R. (2007). Child and youth care in higher education. In H. Grietens, E. J. Knorth, P. Durning, & J. E. Dumas (Eds.), *Promoting competence in children and families: scientific perspectives on resilience and vulnerability* (pp. 375-400).
	
Dieser, R. B., Magnuson, D., & Scholl, K. (2005). Critically rethinking the benefits-based approach from a cross-cultural perspective. *Philosophy of Therapeutic Recreation: Ideas and Issues,* Volume III (pp. 59-72). National Therapeutic Recreation and Park Association.
	
Scott, D., & Magnuson, D. (2005) Integrating spiritual development into child and youth care programs and institutions. In Benson, P. L., Roehlkepartain, E. C., King, P. E., & Wagener, L. (Eds.), *The Handbook of spiritual development in childhood and adolescence (pp. 445-457).* Thousand Oaks, CA: Sage Publications. http://sk.sagepub.com/reference/hdbk_childspiritdev/n31.xml?term=Magnuson

Baldwin, C., Hutchinson, S. L., Magnuson, D. (2004). Program theory: A framework for theory-driven programming and evaluation. *Therapeutic Recreation Journal*, 34, 16-21.
	
Baldwin, C., Persing, J., & Magnuson, D. (2004). The role of theory in research and evaluation about adventure education. *Journal of Experiential Education,* 26(3), 167-183. https://doi.org/10.1177/105382590402600307
	
Coleman, M., Magnuson, D., Randall, S., & Stringer, A.  (2003). Situated friendship: Goal and identity in an after-school girls program.  *Relational Child & Youth Care Practice 16*(1), 21-34.
	
Magnuson, D., Baldwin, C., Baizerman, M., & Stringer, A. (2003). Adolescence or youth?  Background to developmental practice. *Journal of Child & Youth Care Work, 18*. 60-70.
	
Magnuson, D., Baizerman, M., & Lundgren, K. (2003). Challenges to discernment in religious education. *Religion and Education, 30*(2), 45-61.
	
Magnuson, D., & Burger, L. (2002). Developmental supervision in residential care. *Journal of Child and Youth Care, 15*(2), 9-22.
	
Magnuson, D., Hudson, S., & Baldwin, C. (2002). Community youth development reconsidered: A look at some origins of our practices. *Community Youth Development Anthology*, 55-62.
	
Magnuson, D., Baizerman, M., & Stringer, A. (2001). A moral praxis of child and youth care work. *Journal of Child and Youth Care, 15-16*, 302-312.
	
Richter, D., Magnuson, D., & Baizerman, M. (1998). Reconceiving youth ministry. *Religious Education, 93*(3), 340-357.
	
Magnuson, D. (1997). A response to “Residential Treatment and its Alternatives:” Toward a broader paradigm. *Child and Youth Care Forum, 26*(1), 57-61.
	
Beker, J., & Magnuson, D. (Eds.). (1996). *Residential education as an option for at-risk youth.* New York:  Haworth Press. 
	
Magnuson, D. (1996).  Essential moral sources of ethical standards in child and youth care work. *Child and Youth Care Forum, 24*(6), 405-411.
	
Magnuson, D. (1996). Empirical research and prescriptive models. *Child and Youth Care Forum*, 25(5), 293-296.
	
Baizerman, M., & Magnuson, D. (1996).  Do we still need youth as a social stage?  Young: *Nordic Journal of Youth Research, 4*(3), 48-60.
	
Magnuson, D., Bachman, R., & Theunissen, V. (1996).  Perspective taking and socialization of staff. *Child and Youth Care Forum, 25*(6), 379-392.
	
Beker, J., & Magnuson, D. (1996).  Residential education: Some questions, some suggestions, and a look ahead.  *Residential Treatment for Children and Youth, 13*(3), 117-124.
	
Beker, J., & Magnuson, D. (1996). Residential education as an option for at-risk youth: Learning from the Israeli experience. *Residential Treatment for Children & Youth, 13*(3), 3-48.
	
Magnuson, D., Barnes, F. H., & Beker, J. (1996). Human development imperatives in the organization of group care programs: A practical approach. *Residential Treatment for Children and Youth, 13*(3), 85-97.
	
Johnson, D. W., Johnson, R. T., Dudley, B., Ward, M., & Magnuson, D. (1995).  The impact of peer mediation training on the management of school and home conflicts.  *American Educational Research Journal, 32*(4), 829-844.
	
Johnson, D. W., Johnson, R. T., Dudley, B., & Magnuson, D. (1995). Training elementary students to manage conflict.  *Journal of Social Psychology, 135*(6), 673-686.
	
Magnuson, D. (1994). Responding with restraint. *Child and Youth Care Forum, 23*(1), 33-36.